### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by dcabro** [ChilliBits/particulate-matter-app#384]
As of 9th of November, the application does not show any new data. My sensor is configured to push the data to Feinstaub-App as it was before (no change on my end). If this application is being decommissioned, you should at least notify your users...

**Comment by marcauberer** [comment]
We currently have a server outage. A fix is in the work, please be patient ...

**Comment by dcabro** [comment]
Okay thanks

**Comment by dcabro** [comment]
It's working again. Thank you!
