### ISSUE TITLE
Can't turn off alarming for favorites anymore once it was activated

### ISSUE THREAD

**Issue by tom-r** [ChilliBits/particulate-matter-app#51]
Installed the app 2 weeks ago (and today again), defined 2 favorites and monitored it for a day or 2. Then I turned on alarming when threshold exeeds (with the slider in the settings).
Kept it like this for a couple of days, but as the 2 favorites trigger the alarm all day long, I tried to turn off the alarming with the slider.
It doesn't work. Although the slider is 'off' they still trigger alarms.
I removed the favorites, cleared the sensor data, re-set the 2 favorites and here I go again with alarms ...
I uninstalled the app this morning, and reinstalled it, turned off the alarming slider (was on by default) and set my 2 favorites : here I go again with alarms ...
I'm running Android 8.

Please review and fix.

**Comment by marcauberer** [comment]
The bug is fixed. We added a new settings option to completely disable threshold notifications. There already was an option to disable breakdown notifications, so it should now be a seamless experience. The change will be included in the next upcoming update.
