### ISSUE TITLE
Feature request : remember last chart zoom state upon app restart

### ISSUE THREAD

**Issue by tom-r** [ChilliBits/particulate-matter-app#52]
Whenever I start the app, the chart displays a N 0° E 0° position centered on the screen, and I can see whole Africa.
That doesn't make sense, a you have to zoom in again and again to the same positions.
Would be nice if the app could remember the last position and zoom level and use it for the next start.

I have my GPS turned off by default (sucks too much energy), so I can't tell how the app behaves with GPS-on.

BR,
Thomas

**Comment by marcauberer** [comment]
Normally it zooms to the users country, even without gps. If you enable gps, it shows your current location on the map and you can zoom in to this position by tapping on the 'zoom-in button'. We'll look, if we can realize your suggestion.

**Comment by tom-r** [comment]
This is how it comes up upon start of the app : 
![Screenshot_0-0position](https://user-images.githubusercontent.com/1923035/73132568-1fcd5100-401d-11ea-8dce-fa8fee6418ab.jpeg)

According to your comment it should show Austria or Germany then ..

**Comment by marcauberer** [comment]
Okay. This is a strange behavior. We'll try to fix that

**Comment by marcauberer** [comment]
The feature was just added to the app. Will be available with the next update! Stay tuned.
Thanks for the feature request. This issue will be closed at release of the update.
